# Generated by Django 5.1.4 on 2025-04-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='fist',
            new_name='first',
        ),
    ]
